from pydantic import Field

q = Field(..., title="查询内容")
# noinspection PyShadowingBuiltins
id = Field(..., title="唯一标志")
app = Field(..., title="APP 名称")
name = Field(..., title="名称")
applied = Field(..., title="是否已经应用")
app_label = Field(..., title="APP 标签")
model = Field(..., title="模块")
content_type_id = Field(..., title="内容类型ID")
codename = Field(..., title="???")
group_id = Field(..., title="分组ID")
permission_id = Field(..., title="权限ID")
password = Field(..., title="密码")
last_login = Field(None, title="上次登陆时间")
is_superuser = Field(..., title="是否是超级用户")
username = Field(..., title="账号")
first_name = Field(..., title="名")
last_name = Field(..., title="姓")
email = Field(..., title="电子邮箱")
is_staff = Field(..., title="是否为员工")
is_active = Field(..., title="是否激活", description="没有激活的不允许使用")
user_id = Field(..., title="用户的唯一ID")
date_joined = Field(..., title="加入日期")
action_time = Field(..., title="动作时间")
object_id = Field(..., title="对象的ID")
object_repr = Field(..., title="对象的字符串表示")
action_flag = Field(..., title="动作标签")
change_message = Field(..., title="修改信息")
event = Field(..., title="时间名称")
before = Field(..., title="前值")
delta = Field(..., title="变化值")
ctime = Field(..., title="创建时间")
nickname = Field("***", title="昵称")
score = Field(0, title="积分")
mobile = Field(..., title="手机号码")
order_platform = Field(..., title="订单平台")
order_no = Field(..., title="订单号")
order_parent_no = Field(..., title="订单组号")
order_num = Field(1, title="购买数量")
order_ctime = Field(..., title="订单创建时间")
order_status = Field(..., title="订单状态")
pay_price = Field(..., title="付款价格")
pay_time = Field(..., title="支付时间")
end_time = Field(..., title="结束时间")
item_id = Field(..., title="商品ID")
item_title = Field(..., title="商品名称")
item_pic = Field(..., title="商品主图")
item_price = Field(..., title="商品价格")
item_category = Field(..., title="商品分类")
shop_title = Field(..., title="商家名称")
income = Field(..., title="收入")
status = Field(..., title="状态")
mtime = Field(..., title="最近修改时间")
session_key = Field(..., title="会话 key")
session_data = Field(..., title="会话 数据")
expire_date = Field(..., title="过期时间")
token = Field(..., title="令牌")
counter = Field(..., title="计数器")
code = Field(..., title="二维码CODE")
key = Field(..., title="key")
value = Field(..., title="value")

device = Field(..., title="设备推送标志")
uptime = Field(..., title="上次上线时间")

msg_title = Field(..., title="消息的标题")
msg_content = Field(..., title="消息的内容")
msg_type = Field(..., title="消息的类型", description="内部使用, 不对外公开")
client_type = Field(..., title="内部使用")
client_data = Field(..., title="内部使用")
